# Generated by Django 5.0 on 2023-12-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='name',
            new_name='name_1',
        ),
    ]
